#!/bin/bash

set -e

if [[ -z "$*" ]]; then
cat - <<USAGE
Usage: $0 <cutie...>

Set environment variable $<name>_HUGGABLE to define if a cutie should be hugged.
A value of 1 means the cutie would like hugs. If the variable is not set, or set
to any other variable, it is assumed the cutie would prefer empathy.
USAGE
exit 1
fi

for CUTIE in "$@"; do
    CUTIE_NAME=${CUTIE// /_}
    eval HUGGABLE=\$"${CUTIE_NAME^^}_HUGGABLE"
    if [[ ! -z "$HUGGABLE" ]] && [[ "$HUGGABLE" = 1 ]]; then
        echo "Hugs for $CUTIE!"
    else
        echo "Empathy for $CUTIE!"
    fi
done
